sudo: required
services:
    - docker

before_install:
    - docker build -t abhipin286/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run abhipin286/react-test npm test -- --coverage

after_success:
    - docker build -t abhipin286/multi-client ./client
    - docker build -t abhipin286/multi-nginx ./nginx
    - docker build -t abhipin286/multi-server ./server
    - docker build -t abhipin286/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push abhipin286/multi-client
    - docker push abhipin286/multi-nginx
    - docker push abhipin286/multi-server
    - docker push abhipin286/multi-worker
